### ISSUE TITLE
sailfish.def.json missing? Cura 2.7 Beta.

### ISSUE THREAD

**Issue by colinws** [markwal/Cura-FFCP#1]
Using Cura 2.7 Beta, new, clean install on Windows 10, the definitions aren't loading due to a missing resource for the sailfish definition that the ffcp profile inherits from. Not sure if this file is missing from the repository or if there has been a change in Cura.

> 2017-08-03 09:30:55,045 - DEBUG - UM.Settings.DefinitionContainer.getConfigurationTypeFromSerialized [227]: Could not get configuration type: Could not find resource ('sailfish.def.json',) in 8
> 2017-08-03 09:30:55,053 - ERROR - UM.Logger.logException [76]: Exception: Could not deserialize container ffcp
> 2017-08-03 09:30:55,080 - ERROR - UM.Logger.logException [80]: Traceback (most recent call last):
> 2017-08-03 09:30:55,088 - ERROR - UM.Logger.logException [80]:   File "D:/2.7/build/inst/lib/python3.5/site-packages/UM\Settings\ContainerRegistry.py", line 204, in load
> 2017-08-03 09:30:55,096 - ERROR - UM.Logger.logException [80]:   File "D:/2.7/build/inst/lib/python3.5/site-packages/UM\Settings\DefinitionContainer.py", line 284, in deserialize
> 2017-08-03 09:30:55,105 - ERROR - UM.Logger.logException [80]:   File "D:/2.7/build/inst/lib/python3.5/site-packages/UM\Settings\Interfaces.py", line 96, in deserialize
> 2017-08-03 09:30:55,114 - ERROR - UM.Logger.logException [80]:   File "D:/2.7/build/inst/lib/python3.5/site-packages/UM\Settings\Interfaces.py", line 101, in __updateSerialized
> 2017-08-03 09:30:55,122 - ERROR - UM.Logger.logException [80]:   File "D:/2.7/build/inst/lib/python3.5/site-packages/UM\Settings\DefinitionContainer.py", line 249, in getVersionFromSerialized
> 2017-08-03 09:30:55,131 - ERROR - UM.Logger.logException [80]:   File "D:/2.7/build/inst/lib/python3.5/site-packages/UM\Settings\DefinitionContainer.py", line 235, in _readAndValidateSerialized
> 2017-08-03 09:30:55,139 - ERROR - UM.Logger.logException [80]:   File "D:/2.7/build/inst/lib/python3.5/site-packages/UM\Settings\DefinitionContainer.py", line 259, in _preprocessParsedJson
> 2017-08-03 09:30:55,148 - ERROR - UM.Logger.logException [80]:   File "D:/2.7/build/inst/lib/python3.5/site-packages/UM\Settings\DefinitionContainer.py", line 335, in _resolveInheritance
> 2017-08-03 09:30:55,152 - DEBUG - UM.LockFile._waitLockFileDisappear [38]: Waiting for lock file in local config dir to disappear...
> 2017-08-03 09:30:55,160 - ERROR - UM.Logger.logException [80]:   File "D:/2.7/build/inst/lib/python3.5/site-packages/UM\Settings\DefinitionContainer.py", line 323, in _loadFile
> 2017-08-03 09:30:55,169 - ERROR - UM.Logger.logException [80]:   File "D:/2.7/build/inst/lib/python3.5/site-packages/UM\Resources.py", line 75, in getPath
> 2017-08-03 09:30:55,177 - ERROR - UM.Logger.logException [80]: FileNotFoundError: Could not find resource ('sailfish.def.json',) in 8

**Comment by markwal** [comment]
I just made this project to save my WIP from 15.10.  Haven't actually done anything with it.
